version: "3.8"

services:
  database:
    image: postgres:13-bullseye
    restart: always
    container_name: postgresdb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: Qb8B[uE{c!Nn]}qFU,TV)'ZGrR52dK
      POSTGRES_USER: toor
      POSTGRES_DB: inventory
    networks:
      - app-network
    volumes:
      - ./db_scripts:/docker-entrypoint-initdb.d
      - data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    container_name: brm-backend
    depends_on:
      - database
    ports:
      - "3000:3000"
    networks:
      - app-network
    links:
      - database
    environment:
      PORT: 3000
      DB_DSN: postgres://toor:Qb8B[uE{c!Nn]}qFU,TV)'ZGrR52dK@database:5432/inventory
      JWT_SECRET: 5AC04E28682AE61CC6A979CAB4D6CEF96933B26DB38FABB335A9FC88FB0623CE1637F7936B4C9C32392E1ED2157D1565935D5D871418E0DB6893A90706FD8269
    volumes:
      - ./backend/data-storage:/app/data-storage

  # frontend:
  #   build: 
  #     context: ./frontend
  #   container_name: brm-frontend
  #   depends_on:
  #     - backend
  #   ports:
  #     - "9000:9000"
  #   networks:
  #     - app-network
  #   links:
  #     - backend
  #   environment:
  #     PORT: 9000
  #     VITE_BACKEND_URL_BASE: http://localhost:3000/api/V1

networks:
  app-network:

volumes:
  data:
    driver: local
